# branches:
#   only:
#     - master
language: node_js
node_js:
  - "4.3"
env:
  global:
    - COVERAGE_OPTION='./node_modules/babel-istanbul/lib/cli.js cover -x **/spec/**'
    - CXX=g++-4.8
  matrix:
    - MONGODB_VERSION=2.6.11
    - MONGODB_VERSION=3.0.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules/
after_success: ./node_modules/.bin/codecov
